version: '3.8'

services:
  db:
    image: mysql:8
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql

  app:
    image: snaike7/api_projet_annuel
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    volumes:
      - ./scripts:/app/scripts
    depends_on:
      - db
    entrypoint: ["/app/scripts/wait-for-it.sh", "db:3306", "--", "npm", "run", "start"]

volumes:
  db_data:
